### ISSUE TITLE
KendoUI components -no example shows the corresponding control

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#68]
All the list of samples demos for kendo, don't display the related control

for example. kendoAutocomplete
![image](https://user-images.githubusercontent.com/7750628/165388782-563955dd-1320-4431-87c7-22a0beb2f3bc.png)

kendoDropdownList is the only that had a control displayed but dont correspond 

this is diaplayed
![image](https://user-images.githubusercontent.com/7750628/165388909-7179a989-4846-4142-abc1-69b83040e55d.png)

must be displayed
![image](https://user-images.githubusercontent.com/7750628/165388938-937e8290-35ee-4464-9c9d-d5c7bf847faa.png)

**Comment by LRufenacht** [comment]
@paulcordova are you using demo.wisej.com/Kendo or a local version?
Can you verify the scripts are loaded from CDN in the browser console?

**Comment by paulcordova** [comment]
@LRufenacht I'm using demo in browser
Here sample of what I get

![Wisej-DemoBrowser-Kendo-Error](https://user-images.githubusercontent.com/7750628/166465935-51429e53-e102-487b-a751-135888294706.gif)

**Comment by LRufenacht** [comment]
Can you expand the cultures folder?
Please check the Network or Console tab to see if you get errors for missing resources.

**Comment by LRufenacht** [comment]
Found the issue, updating

**Comment by paulcordova** [comment]
Last test still fail in Chrome from my side
![image](https://user-images.githubusercontent.com/7750628/166493784-9b666933-753f-49e8-886f-b6a3814eb308.png)

But in FireFox in spanish settings runs OK
![image](https://user-images.githubusercontent.com/7750628/166493848-05e24582-ae09-44a4-841f-22e5dc1b2d8a.png)

**Comment by LRufenacht** [comment]
Please try again, should be fixed.

The issue was the value of `Application.CurrentCulture.Name` for your Chrome is "es", and their CDN doesn't have a value for that. I've updated all the premium extensions to try to get the full name for the localization (i.e. es-ES or es-CL).

**Comment by paulcordova** [comment]
Chrome in EN is OK
![image](https://user-images.githubusercontent.com/7750628/166502383-2fd5ac8f-5a2c-43fe-9b08-27f985116142.png)

Chrome in ES still fail :-(
![image](https://user-images.githubusercontent.com/7750628/166502444-6e58a921-4a09-4175-9455-56cb7c93419b.png)

**Comment by paulcordova** [comment]
In FireFox in ES work Ok

![image](https://user-images.githubusercontent.com/7750628/166502979-a79705ca-9ffd-4c84-ae69-bd028e166072.png)
