### ISSUE TITLE
ejPivotTreeMap – don’t load control

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#72]
![image](https://user-images.githubusercontent.com/7750628/165406153-544f5082-6907-4139-a768-7bea97dc2392.png)

**Comment by LRufenacht** [comment]
@paulcordova running locally or on demo.wisej.com/demos?
Please check that the cdn scripts are being loaded correctly in the browser.

**Comment by paulcordova** [comment]
@LRufenacht  From on demo.wisej.com/demos?
Today I cant load Syncfusion 2 samples as comment in
https://github.com/iceteagroup/Wisej-DemoBrowser/issues/80

**Comment by LRufenacht** [comment]
@paulcordova it should be working now. please reopen if it doesn't.

**Comment by LRufenacht** [comment]
The issue was that one of the scripts was trying to load an insecure resource.

**Comment by paulcordova** [comment]
Still not load for me
Edge Browser

![image](https://user-images.githubusercontent.com/7750628/166494910-12e6ff6c-0d69-4b06-886d-6348dd7ad4c9.png)

**Comment by lucapivato** [comment]
BTW, all the tests are misaligned.

![](https://user-images.githubusercontent.com/37640802/166495884-ab9663b0-1f0d-43fb-aad6-7e9d23abdc13.png)

**Comment by LRufenacht** [comment]
Can you try clearing your cache @paulcordova I just tried on three different machines and all work okay.
Otherwise, please send the Chrome Console and Network tab.

**Comment by paulcordova** [comment]
Only the PivotTreeMap dont work, all the others runs Ok

Console
![image](https://user-images.githubusercontent.com/7750628/166506678-dfb78d78-d22f-4e67-805b-df71715d3b09.png)

NetWork
![image](https://user-images.githubusercontent.com/7750628/166506721-a3ba4871-96a4-423e-96e0-63216156e85a.png)

Cant reach this two Js files
https://cdn.syncfusion.com/js/assets/i18n/ej.culture.es-419.min.js
https://cdn.syncfusion.com/19.3.0.43/js/l10n/ej.localetexts.es-419.min.js

![image](https://user-images.githubusercontent.com/7750628/166506851-98525e3a-56a0-4d06-9a0a-ca89eee934a6.png)

![image](https://user-images.githubusercontent.com/7750628/166506876-f44f865e-e768-4276-a431-cb02d78d62fc.png)
