### ISSUE TITLE
DevExtreme - dxChart get blank after apply Update button

### ISSUE THREAD

**Issue by paulcordova** [iceteagroup/Wisej-DemoBrowser#99]
After click Update button with or without change properties, the chart get blank

![image](https://user-images.githubusercontent.com/7750628/167955176-3fabe8b0-2d4b-4fb1-94ad-a005e3037efd.png)

**Comment by keevBush** [comment]
Fixed

**Comment by LRufenacht** [comment]
@keevBush it still happens for me when I use the latest code from GitHub.
